/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bhrobotics.morcontrol.io;

public class DeviceType implements org.apache.thrift.TEnum {

  public static final DeviceType PWM = new DeviceType(0);
  public static final DeviceType SOLENOID = new DeviceType(1);
  public static final DeviceType RELAY = new DeviceType(2);
  public static final DeviceType DIGITAL_INPUT = new DeviceType(3);
  public static final DeviceType ANALOG_INPUT = new DeviceType(4);
  public static final DeviceType ENCODER = new DeviceType(5);

  private final int value;

  private DeviceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DeviceType findByValue(int value) { 
    switch (value) {
      case 0:
        return PWM;
      case 1:
        return SOLENOID;
      case 2:
        return RELAY;
      case 3:
        return DIGITAL_INPUT;
      case 4:
        return ANALOG_INPUT;
      case 5:
        return ENCODER;
      default:
        return null;
    }
  }
}
